export const GET_INVITE_REQUEST = "GET_INVITE_REQUEST";
export const GET_INVITE_SUCCESS = "GET_INVITE_SUCCESS";
export const GET_INVITE_FAILURE = "GET_INVITE_FAILURE";

export const ADD_INVITE_REQUEST = "ADD_INVITE_REQUEST";
export const ADD_INVITE_SUCCESS = "ADD_INVITE_SUCCESS";
export const ADD_INVITE_FAILURE = "ADD_INVITE_FAILURE";

export const UPDATE_INVITE_REQUEST = "UPDATE_INVITE_REQUEST";
export const UPDATE_INVITE_SUCCESS = "UPDATE_INVITE_SUCCESS";
export const UPDATE_INVITE_FAILURE = "UPDATE_INVITE_FAILURE";

export const DELETE_INVITE_REQUEST = "DELETE_INVITE_REQUEST";
export const DELETE_INVITE_SUCCESS = "DELETE_INVITE_SUCCESS";
export const DELETE_INVITE_FAILURE = "DELETE_INVITE_FAILURE";
